version: "3.3"
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 9000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.proje.rule=Host(`proje.boyutyazilim.com`)"
      - "traefik.http.routers.proje.entrypoints=https"
      - "traefik.http.routers.proje.tls.certresolver=http"

networks:
  proxy:
    external: true
