version: "3.3"
services:
  proje:
    image: wordpress:latest
    ports:
      - 9005:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: proje
    volumes:
      - /wp-app:/var/www/html # Full wordpress project
      - /wp-plugins/:/var/www/html/wp-content/plugins/ # Plugin development
      - /wp-themes/:/var/www/html/wp-content/themes/ # Theme development
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.proje.rule=Host(`proje.boyutyazilim.com`)"
      - "traefik.http.routers.proje.entrypoints=https"
      - "traefik.http.routers.proje.tls.certresolver=http"

networks:
  proxy:
    external: true

volumes:
  wp-plugins:
  wp-themes:
  wp-app:
